-- CONSOLIDATED MIGRATION: All tables for Metodo Sature Store
-- Run this entire file in Supabase SQL Editor
-- It drops old tables if they exist and recreates them to match the JS code

-- =============================================
-- 1. shared_licenses (keys generated by admin + resellers)
-- =============================================
DROP TABLE IF EXISTS public.license_devices CASCADE;
DROP TABLE IF EXISTS public.shared_licenses CASCADE;

CREATE TABLE public.shared_licenses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  license_key TEXT UNIQUE NOT NULL,
  plan_type TEXT NOT NULL DEFAULT 'basic',
  max_devices INTEGER NOT NULL DEFAULT 2,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked', 'expired')),
  expires_at TIMESTAMPTZ,
  owner TEXT,
  price NUMERIC(10,2),
  created_by TEXT DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  revoked_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sl_license_key ON public.shared_licenses(license_key);
CREATE INDEX IF NOT EXISTS idx_sl_status ON public.shared_licenses(status);
CREATE INDEX IF NOT EXISTS idx_sl_plan_type ON public.shared_licenses(plan_type);

ALTER TABLE public.shared_licenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "sl_select" ON public.shared_licenses FOR SELECT USING (true);
CREATE POLICY "sl_insert" ON public.shared_licenses FOR INSERT WITH CHECK (true);
CREATE POLICY "sl_update" ON public.shared_licenses FOR UPDATE USING (true);
CREATE POLICY "sl_delete" ON public.shared_licenses FOR DELETE USING (true);

-- =============================================
-- 2. license_devices (device tracking)
-- =============================================
CREATE TABLE public.license_devices (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  license_key TEXT NOT NULL,
  device_id TEXT NOT NULL,
  first_seen TIMESTAMPTZ DEFAULT NOW(),
  last_seen TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(license_key, device_id)
);

CREATE INDEX IF NOT EXISTS idx_ld_key ON public.license_devices(license_key);

ALTER TABLE public.license_devices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "ld_all" ON public.license_devices FOR ALL USING (true);

-- =============================================
-- 3. resellers
-- =============================================
DROP TABLE IF EXISTS public.sales CASCADE;
DROP TABLE IF EXISTS public.clients CASCADE;
DROP TABLE IF EXISTS public.resellers CASCADE;

CREATE TABLE public.resellers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  whatsapp TEXT,
  password TEXT,
  tier TEXT NOT NULL DEFAULT 'bronze' CHECK (tier IN ('bronze', 'prata', 'ouro', 'diamante')),
  keys_limit INTEGER NOT NULL DEFAULT 20,
  keys_used INTEGER NOT NULL DEFAULT 0,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_r_email ON public.resellers(email);
CREATE INDEX IF NOT EXISTS idx_r_tier ON public.resellers(tier);

ALTER TABLE public.resellers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "r_select" ON public.resellers FOR SELECT USING (true);
CREATE POLICY "r_insert" ON public.resellers FOR INSERT WITH CHECK (true);
CREATE POLICY "r_update" ON public.resellers FOR UPDATE USING (true);
CREATE POLICY "r_delete" ON public.resellers FOR DELETE USING (true);

-- =============================================
-- 4. sales
-- =============================================
CREATE TABLE public.sales (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  reseller_id UUID REFERENCES public.resellers(id) ON DELETE SET NULL,
  license_key TEXT,
  plan_type TEXT,
  client_name TEXT,
  price NUMERIC(10,2) DEFAULT 0,
  commission NUMERIC(10,2) DEFAULT 0,
  commission_pct NUMERIC(5,2) DEFAULT 0,
  status TEXT DEFAULT 'completed',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_s_reseller ON public.sales(reseller_id);
CREATE INDEX IF NOT EXISTS idx_s_date ON public.sales(created_at);

ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
CREATE POLICY "s_select" ON public.sales FOR SELECT USING (true);
CREATE POLICY "s_insert" ON public.sales FOR INSERT WITH CHECK (true);
CREATE POLICY "s_update" ON public.sales FOR UPDATE USING (true);
CREATE POLICY "s_delete" ON public.sales FOR DELETE USING (true);

-- =============================================
-- 5. clients
-- =============================================
CREATE TABLE public.clients (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  reseller_id UUID REFERENCES public.resellers(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  contact TEXT,
  license_type TEXT,
  license_key TEXT,
  price NUMERIC(10,2) DEFAULT 0,
  status TEXT DEFAULT 'active',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_c_reseller ON public.clients(reseller_id);
CREATE INDEX IF NOT EXISTS idx_c_license ON public.clients(license_key);

ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "c_select" ON public.clients FOR SELECT USING (true);
CREATE POLICY "c_insert" ON public.clients FOR INSERT WITH CHECK (true);
CREATE POLICY "c_update" ON public.clients FOR UPDATE USING (true);
CREATE POLICY "c_delete" ON public.clients FOR DELETE USING (true);

-- =============================================
-- 6. Insert hardcoded licenses so they show in admin
-- =============================================
INSERT INTO public.shared_licenses (license_key, plan_type, max_devices, status, owner, created_at, created_by)
VALUES
  ('VITALICIO-3437-37773-37737', 'life', 5, 'active', 'Sature (Dono)', '2025-01-01T00:00:00Z', 'hardcoded'),
  ('SATURE-ADMIN-MASTER', 'life', 5, 'active', 'Admin Master', '2025-01-01T00:00:00Z', 'hardcoded'),
  ('SATURE-LIFE-2026', 'life', 5, 'active', 'Usuario Life', '2026-01-01T00:00:00Z', 'hardcoded')
ON CONFLICT (license_key) DO NOTHING;
